# Generated by Django 4.1.3 on 2024-05-10 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=50, verbose_name='Movie Name')),
                ('m_desc', models.CharField(max_length=50, verbose_name='Movie Description')),
                ('m_image', models.ImageField(upload_to='pics/', verbose_name='Movie Image')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
        migrations.CreateModel(
            name='SetMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.CharField(max_length=50, verbose_name='Show Time')),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('price', models.IntegerField()),
                ('seats', models.CharField(default='', max_length=100)),
                ('active', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.moviemaster')),
            ],
            options={
                'verbose_name': 'Set Movie',
                'verbose_name_plural': 'Set Movies',
            },
        ),
    ]
