# Generated by Django 4.1.3 on 2024-05-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterModelOptions(
            name='moviemaster',
            options={},
        ),
        migrations.AlterModelOptions(
            name='setmovie',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='moviemaster',
            unique_together={('m_name', 'm_desc', 'm_image')},
        ),
        migrations.AlterUniqueTogether(
            name='setmovie',
            unique_together={('active', 'show', 'start_time', 'end_time')},
        ),
    ]
